# Generated by Django 5.2.6 on 2025-09-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='mobile',
        ),
    ]
