# Generated by Django 5.2.6 on 2025-09-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_phone_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-vector%2Featery-logo&psig=AOvVaw1c5Sd6ltPFc9L0uhY2gaj6&ust=1758085101490000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCNDGgMG_3I8DFQAAAAAdAAAAABAE')),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
